apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}

      initContainers:
        - name: download-tools
          image: alpine:3.8
          command:
            - sh
            - -c
          args:
            - |
              wget -qO- https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.7/kustomize_v4.5.7_linux_amd64.tar.gz | tar -xvzf - &&
              mv kustomize /custom-tools/kustomize_4_5_7
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/
              name: custom-tools
              subPath: kustomize_4_5_7
