apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: "https://github.com/alex92ch/test"
    targetRevision: HEAD
    path: argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: mongodb-operator
spec:
  project: mongodb-operator
  source:
    repoURL: "https://github.com/alex92ch/test"
    targetRevision: HEAD
    path: mongodb-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mongodb-operator
