apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  # Project description
  description: Cluster Infrastructure

  # Only permit applications to deploy to any namespace in the same cluster
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  # Allo

  # Enables project orphaned resource monitoring.
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mongodb-operator
  namespace: mongodb-operator
spec:
  # Project description
  description: mongodboperator

  # Allow manifests to deploy from cluster-infra.git and us_neuvector.git Git repos

  # Only permit applications to deploy to any namespace in the same cluster
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  # Allo
  clusterResourceWhitelist:
    - group: "authorization.openshift.io"
      kind: "ClusterRole"
    - group: "rbac.authorization.k8s.io"
      kind: "ClusterRole"
    - group: "rbac.authorization.k8s.io"
      kind: "ClusterRoleBinding"
    - group: "apiextensions.k8s.io"
      kind: "CustomResourceDefinition"
    - group: ""
      kind: "Namespace"
    - group: "rbacmanager.reactiveops.io"
      kind: "RBACDefinition"
    - group: "user.openshift.io"
      kind: Group

  # Allow certain namespaced-scoped resources to be created
  namespaceResourceWhitelist:
    - group: "redhatcop.redhat.io"
      kind: "ResourceLocker"
    - group: ""
      kind: ConfigMap
    - group: "batch"
      kind: CronJob
    - group: "apps"
      kind: DaemonSet
    - group: "apps"
      kind: Deployment
    - group: "grafana.integreatly.org"
      kind: Grafana
    - group: "grafana.integreatly.org"
      kind: GrafanaDashboard
    - group: "grafana.integreatly.org"
      kind: GrafanaDatasource
    - group: "neuvector.com"
      kind: NvSecurityRule
    - group: "policy"
      kind: PodDisruptionBudget
    - group: "monitoring.coreos.com"
      kind: PrometheusRule
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "route.openshift.io"
      kind: Route
    - group: "bitnami.com"
      kind: SealedSecret
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: "monitoring.coreos.com"
      kind: ServiceMonitor
    - group: "operators.coreos.com"
      kind: Subscription
    - group: "operators.coreos.com"
      kind: "OperatorGroup"
    - group: "redhatcop.redhat.io"
      kind: "Patch"

  # Enables project orphaned resource monitoring.
  orphanedResources:
    warn: false
