apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  # Project description
  description: Cluster Infrastructure
  sourceRepos:
    - "https://github.com/alex92ch/test"
  # Only permit applications to deploy to any namespace in the same cluster
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  # Allo
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # Allow certain namespaced-scoped resources to be created
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Enables project orphaned resource monitoring.
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mongodb-operator
  namespace: mongodb-operator
spec:
  # Project description
  description: mongodboperator
  sourceRepos:
    - "https://github.com/alex92ch/test"
  # Allow manifests to deploy from cluster-infra.git and us_neuvector.git Git repos

  # Only permit applications to deploy to any namespace in the same cluster
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd

    # Allo
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # Allow certain namespaced-scoped resources to be created
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Enables project orphaned resource monitoring.
  orphanedResources:
    warn: false
